# MORISAWA Desktop Managerのリポジトリへのプッシュをトリガーとして
# Goファイルの静的解析をGithubActionで実行する。
# 運用ブランチは[develop]とする。
# 2021/11/02 : AzureをHOSTとして使用する。
# 2021/11/12 : 警告が発生した場合にSlackに通知する。
# 2022/02/01：AWSをHOST Runner とする。

name: golangci-lint

on:
  push:
    branches:
      - feature-FONTELIER_V2**

jobs:
 # 静的解析の実行JOB
  lint-job:

    # mdmserviceの静的解析ではOSに依存する部分があり、windowsとmac環境の
    # それぞれで実行する必要がある。
    # 将来的にAWSへの移行を検討し、テスト段階ではAzure（windows）環境のみ
    # での運用とする。
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest, self-hosted, Azure, AWS]
        os: [AWS]

    runs-on: ${{ matrix.os }}

    steps:
       # リポジトリのチェックアウト
       - name: Repository checkout
         uses: actions/checkout@v2

       # 静的解析（golangci-lint）を実施する
       - name: Run golangci-lint
         run: golangci-lint run -c .golangci_config.yml --tests=False --timeout=30m --max-issues-per-linter 0 --max-same-issues 0 --out-format=colored-line-number ./...
